// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S00236328_classlibrary;

#nullable disable

namespace S00236328_classlibrary.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20250102200729_s00236328")]
    partial class s00236328
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("S00236328_classlibrary.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            DepartureTime = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Rome",
                            DestinationCountry = "Italy",
                            FlightNo = "IT-001",
                            MaxSeats = 110,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightId = 2,
                            DepartureTime = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "London",
                            DestinationCountry = "England",
                            FlightNo = "EN-002",
                            MaxSeats = 110,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightId = 3,
                            DepartureTime = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Paris",
                            DestinationCountry = "France",
                            FlightNo = "FR-001",
                            MaxSeats = 120,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightId = 4,
                            DepartureTime = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Brussels",
                            DestinationCountry = "Belgium",
                            FlightNo = "BE-001",
                            MaxSeats = 88,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightId = 5,
                            DepartureTime = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Dublin",
                            DestinationCountry = "Ireland",
                            FlightNo = "DU-001",
                            MaxSeats = 110,
                            Origin = "London"
                        });
                });

            modelBuilder.Entity("S00236328_classlibrary.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = 1,
                            PassengerName = "Fred Farnell",
                            Passport = "P010203"
                        },
                        new
                        {
                            PassengerId = 2,
                            PassengerName = "Tom McManus",
                            Passport = "P896745"
                        },
                        new
                        {
                            PassengerId = 3,
                            PassengerName = "Bill Trimble",
                            Passport = "P231425"
                        },
                        new
                        {
                            PassengerId = 4,
                            PassengerName = "Freda McDonald",
                            Passport = "P235678"
                        },
                        new
                        {
                            PassengerId = 5,
                            PassengerName = "Mary Malone",
                            Passport = "P214587"
                        },
                        new
                        {
                            PassengerId = 6,
                            PassengerName = "Tom McManus",
                            Passport = "P893482"
                        });
                });

            modelBuilder.Entity("S00236328_classlibrary.PassengerBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaggageCharge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TicketCost")
                        .HasColumnType("REAL");

                    b.Property<int>("TicketType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("PassengerBookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaggageCharge = 30,
                            FlightId = 2,
                            PassengerId = 1,
                            TicketCost = 51.829999999999998,
                            TicketType = 0
                        },
                        new
                        {
                            Id = 2,
                            BaggageCharge = 10,
                            FlightId = 2,
                            PassengerId = 2,
                            TicketCost = 127.0,
                            TicketType = 1
                        },
                        new
                        {
                            Id = 3,
                            BaggageCharge = 10,
                            FlightId = 3,
                            PassengerId = 3,
                            TicketCost = 140.0,
                            TicketType = 1
                        },
                        new
                        {
                            Id = 4,
                            BaggageCharge = 15,
                            FlightId = 4,
                            PassengerId = 4,
                            TicketCost = 50.0,
                            TicketType = 0
                        },
                        new
                        {
                            Id = 5,
                            BaggageCharge = 15,
                            FlightId = 1,
                            PassengerId = 5,
                            TicketCost = 69.0,
                            TicketType = 0
                        },
                        new
                        {
                            Id = 6,
                            BaggageCharge = 10,
                            FlightId = 5,
                            PassengerId = 6,
                            TicketCost = 127.0,
                            TicketType = 1
                        });
                });

            modelBuilder.Entity("S00236328_classlibrary.PassengerBooking", b =>
                {
                    b.HasOne("S00236328_classlibrary.Flight", "Flight")
                        .WithMany("PassengerBookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S00236328_classlibrary.Passenger", "Passenger")
                        .WithMany("PassengerBookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("S00236328_classlibrary.Flight", b =>
                {
                    b.Navigation("PassengerBookings");
                });

            modelBuilder.Entity("S00236328_classlibrary.Passenger", b =>
                {
                    b.Navigation("PassengerBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
